{% set version = "1.3.4" %}

package:
  name: hachoir-parser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hachoir-parser/hachoir-parser-{{ version }}.tar.gz
  sha256: 775be5e10d72c6122b1ba3202dfce153c09ebcb60080d8edbd51aa89aa4e6b3f

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3
    - hachoir-core

test:
  imports:
    - hachoir_parser
    - hachoir_parser.archive
    - hachoir_parser.audio
    - hachoir_parser.common
    - hachoir_parser.container
    - hachoir_parser.file_system
    - hachoir_parser.game
    - hachoir_parser.image
    - hachoir_parser.misc
    - hachoir_parser.network
    - hachoir_parser.program
    - hachoir_parser.video

about:
  home: http://bitbucket.org/haypo/hachoir/wiki/hachoir-parser
  license: GPL 2.0
  summary: 'Package of Hachoir parsers used to open binary files'

extra:
  recipe-maintainers:
    - pmlandwehr
