travis:
  secure:
    BINSTAR_TOKEN: kD7+9E6vX2kQo84xZVCbUm9nfIkPKhVsQr6U4LukuoPGEGdyMt3EX0GZg1rzS7pYlQOIbye2nmJxfEeKb+don/B9t9V3ow44svqkCJMeJqXGdC6cPNvLX5SuI3X4G6xW3pRV+X5iwme7HrTcrHnesMdce5HAG6n7f3j85D0djJgNIHcwHDDnfbQGzGD0PwykvrYoygzcWa8hS6bEMx9dxGQhAHA1sBlfrzh/Gxoe8ZWI0DNNT+Ekt7GHAzYSLVC7n/cf9XQoSqWD2/iMUEtlRCy2w+nXFQ2qD/3fbH/uLxEVAwpnoAU512YdpUC16Fx+KUzfouj7M0u1/v9Uubqf7WzfUt00e1crdXBUC5NfRhHChMC6W4Whzyr1GMl2q0bOZpPKzc6i43E802xy2mk44/XygbUkiAlOl4uTXVX47vcOQK7MUMCR7qRvDoFMawx4jRRT+mkUvrz4nUdVfMz6huuBCt+ZqwHG77lyokvGCO8V3qZioGqQ2STTVLgmipFBgm8jVmiV6xxKtBGccmcQILxeX5Hp7Iw+A/k29rl6bzSR6A6sE1o1k52Y/sa9cKpJmXKOmFnTso/BFGXDoIh2D2UiBzY1iYJGI3xx9r7cRB4CL2tidOVEtqP6n3QBXT1/MUspqSpMts6R43rIWdJ52jK9oBV2kE9QwjTgYHA35JU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
