travis:
  secure:
    BINSTAR_TOKEN: e+ABpmag/Jb5SY9+hc4n4WudSMtsWfZ0D+rGow9VzhzqsqIb92AIojUP3f6JErVfWzbsAmiz5hshetdqIpZe2f4YI+ZFDwz2paC2RnRFuAIkrxlBlPfVAPqojKEudTpHuMYQrFq0BqzgbMS1H4liiokUVQDyCXz2Ed6gXDZ1198XycJv/rWWvGGIj3+u49fL5mYLoNTXbT6RixbLXne0mZDDS7lZpKFmiQLhDa4WEz874pMUY/IvYrhuszfdqVBKvEabn28NIjzGlpVEtbMsPxvpRoNxwHWKebPpdHLWMafkRJghgAr9edCLnWhKePnmhe7+OvR44YWpknBLR7B+J0Y6TsugIkZOhboF4L4OHuyHAGd0Ud1MZ2boOabvmjH1Tf+szyzfK819sHSLkBCPqPhK2QgGTe+DrWuJi1/vU5ygreiZ0yGkXTEJ56zj/dZvwl2L2Ovqr+hLqVe7UblqCWQAbYEAlgTs99XN2sy+LXwshvUuPUIenAtd4Tk61JLuzeHmHep3QhuqGjrhSUVaRqlTuKeCGLNBrIedMn7k3GFgP+En0iHRM3RnbQkQwNGptGJZjcCMealnlge+ZR/cSGY6zZEJXkvrES7Fk28HcpHHNgDnGZHX5sX/1zcgkzWw0ybO9D/MRmWoJOIw40VVJyoVMSa7jUATf5rrBy5MXjk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
